"""Write src/lib/statusCodes.js from asyncua's OPC UA StatusCode table.

The UI decodes a numeric StatusCode into its name and meaning for display --
"BadNoCommunication: Communication with the data source is defined, but not
established ..." rather than a bare 2150694912. Generated, not typed, so a
name can never drift from the code it stands for.

    ../.venv/bin/python scripts/gen_status_codes.py
"""
import json
from pathlib import Path

from asyncua.ua.status_codes import code_to_name_doc

out = Path(__file__).parent.parent / "src" / "lib" / "statusCodes.js"
table = {str(code): [name, doc] for code, (name, doc) in sorted(code_to_name_doc.items())}
out.write_text(
    "// Generated by scripts/gen_status_codes.py from asyncua's StatusCode table.\n"
    "// Do not edit by hand.\n"
    f"export const STATUS_CODES = {json.dumps(table, indent=0, ensure_ascii=False)}\n")
print(f"{len(table)} status codes -> {out}")
