// Generated by scripts/gen_status_codes.py from asyncua's StatusCode table.
// Do not edit by hand.
export const STATUS_CODES = {
"0": [
"Good",
"The operation succeeded."
],
"2949120": [
"GoodSubscriptionTransferred",
"The subscription was transferred to another session."
],
"3014656": [
"GoodCompletesAsynchronously",
"The processing will complete asynchronously."
],
"3080192": [
"GoodOverload",
"Sampling has slowed down due to resource limitations."
],
"3145728": [
"GoodClamped",
"The value written was accepted but was clamped."
],
"9830400": [
"GoodLocalOverride",
"The value has been overridden."
],
"10616832": [
"GoodEntryInserted",
"The data or event was successfully inserted into the historical database."
],
"10682368": [
"GoodEntryReplaced",
"The data or event field was successfully replaced in the historical database."
],
"10813440": [
"GoodNoData",
"No data exists for the requested time range or event filter."
],
"10878976": [
"GoodMoreData",
"More data is available in the time range beyond the number of values requested."
],
"10944512": [
"GoodCommunicationEvent",
"The communication layer has raised an event."
],
"11010048": [
"GoodShutdownEvent",
"The system is shutting down."
],
"11075584": [
"GoodCallAgain",
"The operation is not finished and needs to be called again."
],
"11141120": [
"GoodNonCriticalTimeout",
"A non-critical timeout occurred."
],
"12189696": [
"GoodResultsMayBeIncomplete",
"The server should have followed a reference to a node in a remote server but did not. The result set may be incomplete."
],
"14221312": [
"GoodDataIgnored",
"The request specifies fields which are not valid for the EventType or cannot be saved by the historian."
],
"14417920": [
"GoodEdited",
"The value does not come from the real source and has been edited by the server."
],
"14483456": [
"GoodPostActionFailed",
"There was an error in execution of these post-actions."
],
"14614528": [
"GoodRetransmissionQueueNotSupported",
"The Server does not support retransmission queue and acknowledgement of sequence numbers is not available."
],
"14680064": [
"GoodDependentValueChanged",
"A dependent value has been changed but the change has not been applied to the device."
],
"15400960": [
"GoodSubNormal",
"The value is derived from multiple sources and has the required number of Good sources, but less than the full number of Good sources."
],
"15663104": [
"GoodPasswordChangeRequired",
"The log-on for the user succeeded but the user is required to change the password."
],
"18219008": [
"GoodEdited_DependentValueChanged",
"It is delivered with a dominant Variable value when a dependent Variable has changed but the change has not been applied."
],
"18284544": [
"GoodEdited_DominantValueChanged",
"It is delivered with a dependent Variable value when a dominant Variable has changed but the change has not been applied."
],
"18350080": [
"GoodEdited_DominantValueChanged_DependentValueChanged",
"It is delivered with a dependent Variable value when a dominant or dependent Variable has changed but change has not been applied."
],
"67174400": [
"GoodCascadeInitializationAcknowledged",
"The value source supports cascade handshaking and the value has been Initialized based on an initialization request from a cascade secondary."
],
"67239936": [
"GoodCascadeInitializationRequest",
"The value source supports cascade handshaking and is requesting initialization of a cascade primary."
],
"67305472": [
"GoodCascadeNotInvited",
"The value source supports cascade handshaking, however, the source\"s current state does not allow for cascade."
],
"67371008": [
"GoodCascadeNotSelected",
"The value source supports cascade handshaking, however, the source has not selected the corresponding cascade primary for use."
],
"67567616": [
"GoodFaultStateActive",
"There is a fault state condition active in the value source."
],
"67633152": [
"GoodInitiateFaultState",
"A fault state condition is being requested of the destination."
],
"67698688": [
"GoodCascade",
"The value is accurate, and the signal source supports cascade handshaking."
],
"1073741824": [
"Uncertain",
"The operation was uncertain."
],
"1080819712": [
"UncertainReferenceOutOfServer",
"One of the references to follow in the relative path references to a node in the address space in another server."
],
"1083113472": [
"UncertainNoCommunicationLastUsableValue",
"Communication to the data source has failed. The variable value is the last value that had a good quality."
],
"1083179008": [
"UncertainLastUsableValue",
"Whatever was updating this value has stopped doing so."
],
"1083244544": [
"UncertainSubstituteValue",
"The value is an operational value that was manually overwritten."
],
"1083310080": [
"UncertainInitialValue",
"The value is an initial value for a variable that normally receives its value from another variable."
],
"1083375616": [
"UncertainSensorNotAccurate",
"The value is at one of the sensor limits."
],
"1083441152": [
"UncertainEngineeringUnitsExceeded",
"The value is outside of the range of values defined for this parameter."
],
"1083506688": [
"UncertainSubNormal",
"The data value is derived from multiple sources and has less than the required number of Good sources."
],
"1084489728": [
"UncertainDataSubNormal",
"The aggregate value is derived from multiple values and has less than the required number of Good values."
],
"1086062592": [
"UncertainReferenceNotDeleted",
"The server was not able to delete all target references."
],
"1086324736": [
"UncertainNotAllNodesAvailable",
"The list of references may not be complete because the underlying system is not available."
],
"1088290816": [
"UncertainDominantValueChanged",
"The related EngineeringUnit has been changed but the Variable Value is still provided based on the previous unit."
],
"1088552960": [
"UncertainDependentValueChanged",
"A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is uncertain."
],
"1089601536": [
"UncertainOverRange",
"The value is over the allowed range."
],
"1089667072": [
"UncertainUnderRange",
"The value is under the allowed range."
],
"1107820544": [
"UncertainTransducerInManual",
"The value may not be accurate because the transducer is in manual mode."
],
"1107886080": [
"UncertainSimulatedValue",
"The value is simulated."
],
"1107951616": [
"UncertainSensorCalibration",
"The value may not be accurate due to a sensor calibration fault."
],
"1108279296": [
"UncertainConfigurationError",
"The value may not be accurate due to a configuration issue."
],
"2147483648": [
"Bad",
"The operation failed."
],
"2147549184": [
"BadUnexpectedError",
"An unexpected error occurred."
],
"2147614720": [
"BadInternalError",
"An internal error occurred as a result of a programming or configuration error."
],
"2147680256": [
"BadOutOfMemory",
"Not enough memory to complete the operation."
],
"2147745792": [
"BadResourceUnavailable",
"An operating system resource is not available."
],
"2147811328": [
"BadCommunicationError",
"A low level communication error occurred."
],
"2147876864": [
"BadEncodingError",
"Encoding halted because of invalid data in the objects being serialized."
],
"2147942400": [
"BadDecodingError",
"Decoding halted because of invalid data in the stream."
],
"2148007936": [
"BadEncodingLimitsExceeded",
"The message encoding/decoding limits imposed by the stack have been exceeded."
],
"2148073472": [
"BadUnknownResponse",
"An unrecognized response was received from the server."
],
"2148139008": [
"BadTimeout",
"The operation timed out."
],
"2148204544": [
"BadServiceUnsupported",
"The server does not support the requested service."
],
"2148270080": [
"BadShutdown",
"The operation was cancelled because the application is shutting down."
],
"2148335616": [
"BadServerNotConnected",
"The operation could not complete because the client is not connected to the server."
],
"2148401152": [
"BadServerHalted",
"The server has stopped and cannot process any requests."
],
"2148466688": [
"BadNothingToDo",
"No processing could be done because there was nothing to do."
],
"2148532224": [
"BadTooManyOperations",
"The request could not be processed because it specified too many operations."
],
"2148597760": [
"BadDataTypeIdUnknown",
"The extension object cannot be (de)serialized because the data type id is not recognized."
],
"2148663296": [
"BadCertificateInvalid",
"The certificate provided as a parameter is not valid."
],
"2148728832": [
"BadSecurityChecksFailed",
"An error occurred verifying security."
],
"2148794368": [
"BadCertificateTimeInvalid",
"The certificate has expired or is not yet valid."
],
"2148859904": [
"BadCertificateIssuerTimeInvalid",
"An issuer certificate has expired or is not yet valid."
],
"2148925440": [
"BadCertificateHostNameInvalid",
"The HostName used to connect to a server does not match a HostName in the certificate."
],
"2148990976": [
"BadCertificateUriInvalid",
"The URI specified in the ApplicationDescription does not match the URI in the certificate."
],
"2149056512": [
"BadCertificateUseNotAllowed",
"The certificate may not be used for the requested operation."
],
"2149122048": [
"BadCertificateIssuerUseNotAllowed",
"The issuer certificate may not be used for the requested operation."
],
"2149187584": [
"BadCertificateUntrusted",
"The certificate is not trusted."
],
"2149253120": [
"BadCertificateRevocationUnknown",
"It was not possible to determine if the certificate has been revoked."
],
"2149318656": [
"BadCertificateIssuerRevocationUnknown",
"It was not possible to determine if the issuer certificate has been revoked."
],
"2149384192": [
"BadCertificateRevoked",
"The certificate has been revoked."
],
"2149449728": [
"BadCertificateIssuerRevoked",
"The issuer certificate has been revoked."
],
"2149515264": [
"BadUserAccessDenied",
"User does not have permission to perform the requested operation."
],
"2149580800": [
"BadIdentityTokenInvalid",
"The user identity token is not valid."
],
"2149646336": [
"BadIdentityTokenRejected",
"The user identity token is valid but the server has rejected it."
],
"2149711872": [
"BadSecureChannelIdInvalid",
"The specified secure channel is no longer valid."
],
"2149777408": [
"BadInvalidTimestamp",
"The timestamp is outside the range allowed by the server."
],
"2149842944": [
"BadNonceInvalid",
"The nonce does appear to be not a random value or it is not the correct length."
],
"2149908480": [
"BadSessionIdInvalid",
"The session id is not valid."
],
"2149974016": [
"BadSessionClosed",
"The session was closed by the client."
],
"2150039552": [
"BadSessionNotActivated",
"The session cannot be used because ActivateSession has not been called."
],
"2150105088": [
"BadSubscriptionIdInvalid",
"The subscription id is not valid."
],
"2150236160": [
"BadRequestHeaderInvalid",
"The header for the request is missing or invalid."
],
"2150301696": [
"BadTimestampsToReturnInvalid",
"The timestamps to return parameter is invalid."
],
"2150367232": [
"BadRequestCancelledByClient",
"The request was cancelled by the client."
],
"2150694912": [
"BadNoCommunication",
"Communication with the data source is defined, but not established, and there is no last known value available."
],
"2150760448": [
"BadWaitingForInitialData",
"Waiting for the server to obtain values from the underlying data source."
],
"2150825984": [
"BadNodeIdInvalid",
"The syntax the node id is not valid or refers to a node that is not valid for the operation."
],
"2150891520": [
"BadNodeIdUnknown",
"The node id refers to a node that does not exist in the server address space."
],
"2150957056": [
"BadAttributeIdInvalid",
"The attribute is not supported for the specified Node."
],
"2151022592": [
"BadIndexRangeInvalid",
"The syntax of the index range parameter is invalid."
],
"2151088128": [
"BadIndexRangeNoData",
"No data exists within the range of indexes specified."
],
"2151153664": [
"BadDataEncodingInvalid",
"The data encoding is invalid."
],
"2151219200": [
"BadDataEncodingUnsupported",
"The server does not support the requested data encoding for the node."
],
"2151284736": [
"BadNotReadable",
"The access level does not allow reading or subscribing to the Node."
],
"2151350272": [
"BadNotWritable",
"The access level does not allow writing to the Node."
],
"2151415808": [
"BadOutOfRange",
"The value was out of range."
],
"2151481344": [
"BadNotSupported",
"The requested operation is not supported."
],
"2151546880": [
"BadNotFound",
"A requested item was not found or a search operation ended without success."
],
"2151612416": [
"BadObjectDeleted",
"The object cannot be used because it has been deleted."
],
"2151677952": [
"BadNotImplemented",
"Requested operation is not implemented."
],
"2151743488": [
"BadMonitoringModeInvalid",
"The monitoring mode is invalid."
],
"2151809024": [
"BadMonitoredItemIdInvalid",
"The monitoring item id does not refer to a valid monitored item."
],
"2151874560": [
"BadMonitoredItemFilterInvalid",
"The monitored item filter parameter is not valid."
],
"2151940096": [
"BadMonitoredItemFilterUnsupported",
"The server does not support the requested monitored item filter."
],
"2152005632": [
"BadFilterNotAllowed",
"A monitoring filter cannot be used in combination with the attribute specified."
],
"2152071168": [
"BadStructureMissing",
"A mandatory structured parameter was missing or null."
],
"2152136704": [
"BadEventFilterInvalid",
"The event filter is not valid."
],
"2152202240": [
"BadContentFilterInvalid",
"The content filter is not valid."
],
"2152267776": [
"BadFilterOperandInvalid",
"The operand used in a content filter is not valid."
],
"2152333312": [
"BadContinuationPointInvalid",
"The continuation point provide is longer valid."
],
"2152398848": [
"BadNoContinuationPoints",
"The operation could not be processed because all continuation points have been allocated."
],
"2152464384": [
"BadReferenceTypeIdInvalid",
"The reference type id does not refer to a valid reference type node."
],
"2152529920": [
"BadBrowseDirectionInvalid",
"The browse direction is not valid."
],
"2152595456": [
"BadNodeNotInView",
"The node is not part of the view."
],
"2152660992": [
"BadServerUriInvalid",
"The ServerUri is not a valid URI."
],
"2152726528": [
"BadServerNameMissing",
"No ServerName was specified."
],
"2152792064": [
"BadDiscoveryUrlMissing",
"No DiscoveryUrl was specified."
],
"2152857600": [
"BadSemaphoreFileMissing",
"The semaphore file specified by the client is not valid."
],
"2152923136": [
"BadRequestTypeInvalid",
"The security token request type is not valid."
],
"2152988672": [
"BadSecurityModeRejected",
"The security mode does not meet the requirements set by the server."
],
"2153054208": [
"BadSecurityPolicyRejected",
"The security policy does not meet the requirements set by the server."
],
"2153119744": [
"BadTooManySessions",
"The server has reached its maximum number of sessions."
],
"2153185280": [
"BadUserSignatureInvalid",
"The user token signature is missing or invalid."
],
"2153250816": [
"BadApplicationSignatureInvalid",
"The signature generated with the client certificate is missing or invalid."
],
"2153316352": [
"BadNoValidCertificates",
"The client did not provide at least one software certificate that is valid and meets the profile requirements for the server."
],
"2153381888": [
"BadRequestCancelledByRequest",
"The request was cancelled by the client with the Cancel service."
],
"2153447424": [
"BadParentNodeIdInvalid",
"The parent node id does not to refer to a valid node."
],
"2153512960": [
"BadReferenceNotAllowed",
"The reference could not be created because it violates constraints imposed by the data model."
],
"2153578496": [
"BadNodeIdRejected",
"The requested node id was reject because it was either invalid or server does not allow node ids to be specified by the client."
],
"2153644032": [
"BadNodeIdExists",
"The requested node id is already used by another node."
],
"2153709568": [
"BadNodeClassInvalid",
"The node class is not valid."
],
"2153775104": [
"BadBrowseNameInvalid",
"The browse name is invalid."
],
"2153840640": [
"BadBrowseNameDuplicated",
"The browse name is not unique among nodes that share the same relationship with the parent."
],
"2153906176": [
"BadNodeAttributesInvalid",
"The node attributes are not valid for the node class."
],
"2153971712": [
"BadTypeDefinitionInvalid",
"The type definition node id does not reference an appropriate type node."
],
"2154037248": [
"BadSourceNodeIdInvalid",
"The source node id does not reference a valid node."
],
"2154102784": [
"BadTargetNodeIdInvalid",
"The target node id does not reference a valid node."
],
"2154168320": [
"BadDuplicateReferenceNotAllowed",
"The reference type between the nodes is already defined."
],
"2154233856": [
"BadInvalidSelfReference",
"The server does not allow this type of self reference on this node."
],
"2154299392": [
"BadReferenceLocalOnly",
"The reference type is not valid for a reference to a remote server."
],
"2154364928": [
"BadNoDeleteRights",
"The server will not allow the node to be deleted."
],
"2154430464": [
"BadServerIndexInvalid",
"The server index is not valid."
],
"2154496000": [
"BadViewIdUnknown",
"The view id does not refer to a valid view node."
],
"2154627072": [
"BadTooManyMatches",
"The requested operation has too many matches to return."
],
"2154692608": [
"BadQueryTooComplex",
"The requested operation requires too many resources in the server."
],
"2154758144": [
"BadNoMatch",
"The requested operation has no match to return."
],
"2154823680": [
"BadMaxAgeInvalid",
"The max age parameter is invalid."
],
"2154889216": [
"BadHistoryOperationInvalid",
"The history details parameter is not valid."
],
"2154954752": [
"BadHistoryOperationUnsupported",
"The server does not support the requested operation."
],
"2155020288": [
"BadWriteNotSupported",
"The server does not support writing the combination of value, status and timestamps provided."
],
"2155085824": [
"BadTypeMismatch",
"The value supplied for the attribute is not of the same type as the attribute\"s value."
],
"2155151360": [
"BadMethodInvalid",
"The method id does not refer to a method for the specified object."
],
"2155216896": [
"BadArgumentsMissing",
"The client did not specify all of the input arguments for the method."
],
"2155282432": [
"BadTooManySubscriptions",
"The server has reached its maximum number of subscriptions."
],
"2155347968": [
"BadTooManyPublishRequests",
"The server has reached the maximum number of queued publish requests."
],
"2155413504": [
"BadNoSubscription",
"There is no subscription available for this session."
],
"2155479040": [
"BadSequenceNumberUnknown",
"The sequence number is unknown to the server."
],
"2155544576": [
"BadMessageNotAvailable",
"The requested notification message is no longer available."
],
"2155610112": [
"BadInsufficientClientProfile",
"The client of the current session does not support one or more Profiles that are necessary for the subscription."
],
"2155675648": [
"BadTcpServerTooBusy",
"The server cannot process the request because it is too busy."
],
"2155741184": [
"BadTcpMessageTypeInvalid",
"The type of the message specified in the header invalid."
],
"2155806720": [
"BadTcpSecureChannelUnknown",
"The SecureChannelId and/or TokenId are not currently in use."
],
"2155872256": [
"BadTcpMessageTooLarge",
"The size of the message chunk specified in the header is too large."
],
"2155937792": [
"BadTcpNotEnoughResources",
"There are not enough resources to process the request."
],
"2156003328": [
"BadTcpInternalError",
"An internal error occurred."
],
"2156068864": [
"BadTcpEndpointUrlInvalid",
"The server does not recognize the QueryString specified."
],
"2156134400": [
"BadRequestInterrupted",
"The request could not be sent because of a network interruption."
],
"2156199936": [
"BadRequestTimeout",
"Timeout occurred while processing the request."
],
"2156265472": [
"BadSecureChannelClosed",
"The secure channel has been closed."
],
"2156331008": [
"BadSecureChannelTokenUnknown",
"The token has expired or is not recognized."
],
"2156396544": [
"BadSequenceNumberInvalid",
"The sequence number is not valid."
],
"2156462080": [
"BadConfigurationError",
"There is a problem with the configuration that affects the usefulness of the value."
],
"2156527616": [
"BadNotConnected",
"The variable should receive its value from another variable, but has never been configured to do so."
],
"2156593152": [
"BadDeviceFailure",
"There has been a failure in the device/data source that generates the value that has affected the value."
],
"2156658688": [
"BadSensorFailure",
"There has been a failure in the sensor from which the value is derived by the device/data source."
],
"2156724224": [
"BadOutOfService",
"The source of the data is not operational."
],
"2156789760": [
"BadDeadbandFilterInvalid",
"The deadband filter is not valid."
],
"2157379584": [
"BadRefreshInProgress",
"This Condition refresh failed, a Condition refresh operation is already in progress."
],
"2157445120": [
"BadConditionAlreadyDisabled",
"This condition has already been disabled."
],
"2157510656": [
"BadConditionDisabled",
"Property not available, this condition is disabled."
],
"2157576192": [
"BadEventIdUnknown",
"The specified event id is not recognized."
],
"2157641728": [
"BadNoData",
"No data exists for the requested time range or event filter."
],
"2157772800": [
"BadDataLost",
"Data is missing due to collection started/stopped/lost."
],
"2157838336": [
"BadDataUnavailable",
"Expected data is unavailable for the requested time range due to an un-mounted volume, an off-line archive or tape, or similar reason for temporary unavailability."
],
"2157903872": [
"BadEntryExists",
"The data or event was not successfully inserted because a matching entry exists."
],
"2157969408": [
"BadNoEntryExists",
"The data or event was not successfully updated because no matching entry exists."
],
"2158034944": [
"BadTimestampNotSupported",
"The Client requested history using a TimestampsToReturn the Server does not support."
],
"2158690304": [
"BadInvalidArgument",
"One or more arguments are invalid."
],
"2158755840": [
"BadConnectionRejected",
"Could not establish a network connection to remote server."
],
"2158821376": [
"BadDisconnect",
"The server has disconnected from the client."
],
"2158886912": [
"BadConnectionClosed",
"The network connection has been closed."
],
"2158952448": [
"BadInvalidState",
"The operation cannot be completed because the object is closed, uninitialized or in some other invalid state."
],
"2159017984": [
"BadEndOfStream",
"Cannot move beyond end of the stream."
],
"2159083520": [
"BadNoDataAvailable",
"No data is currently available for reading from a non-blocking stream."
],
"2159149056": [
"BadWaitingForResponse",
"The asynchronous operation is waiting for a response."
],
"2159214592": [
"BadOperationAbandoned",
"The asynchronous operation was abandoned by the caller."
],
"2159280128": [
"BadExpectedStreamToBlock",
"The stream did not return all data requested (possibly because it is a non-blocking stream)."
],
"2159345664": [
"BadWouldBlock",
"Non blocking behaviour is required and the operation would block."
],
"2159411200": [
"BadSyntaxError",
"A value had an invalid syntax."
],
"2159476736": [
"BadMaxConnectionsReached",
"The operation could not be finished because all available connections are in use."
],
"2159542272": [
"BadRequestTooLarge",
"The request message size exceeds limits set by the server."
],
"2159607808": [
"BadResponseTooLarge",
"The response message size exceeds limits set by the client or server."
],
"2159738880": [
"BadEventNotAcknowledgeable",
"The event cannot be acknowledged."
],
"2159869952": [
"BadInvalidTimestampArgument",
"The defined timestamp to return was invalid."
],
"2159935488": [
"BadProtocolVersionUnsupported",
"The applications do not have compatible protocol versions."
],
"2160001024": [
"BadStateNotActive",
"The sub-state machine is not currently active."
],
"2160132096": [
"BadFilterOperatorInvalid",
"An unrecognized operator was provided in a filter."
],
"2160197632": [
"BadFilterOperatorUnsupported",
"A valid operator was provided, but the server does not provide support for this filter operator."
],
"2160263168": [
"BadFilterOperandCountMismatch",
"The number of operands provided for the filter operator was less then expected for the operand provided."
],
"2160328704": [
"BadFilterElementInvalid",
"The referenced element is not a valid element in the content filter."
],
"2160394240": [
"BadFilterLiteralInvalid",
"The referenced literal is not a valid value."
],
"2160459776": [
"BadIdentityChangeNotSupported",
"The server does not support changing the user identity assigned to the session."
],
"2160590848": [
"BadNotTypeDefinition",
"The provided Nodeid was not a type definition nodeid."
],
"2160656384": [
"BadViewTimestampInvalid",
"The view timestamp is not available or not supported."
],
"2160721920": [
"BadViewParameterMismatch",
"The view parameters are not consistent with each other."
],
"2160787456": [
"BadViewVersionInvalid",
"The view version is not available or not supported."
],
"2160852992": [
"BadConditionAlreadyEnabled",
"This condition has already been enabled."
],
"2160918528": [
"BadDialogNotActive",
"The dialog condition is not active."
],
"2160984064": [
"BadDialogResponseInvalid",
"The response is not valid for the dialog."
],
"2161049600": [
"BadConditionBranchAlreadyAcked",
"The condition branch has already been acknowledged."
],
"2161115136": [
"BadConditionBranchAlreadyConfirmed",
"The condition branch has already been confirmed."
],
"2161180672": [
"BadConditionAlreadyShelved",
"The condition has already been shelved."
],
"2161246208": [
"BadConditionNotShelved",
"The condition is not currently shelved."
],
"2161311744": [
"BadShelvingTimeOutOfRange",
"The shelving time not within an acceptable range."
],
"2161377280": [
"BadAggregateListMismatch",
"The requested number of Aggregates does not match the requested number of NodeIds."
],
"2161442816": [
"BadAggregateNotSupported",
"The requested Aggregate is not support by the server."
],
"2161508352": [
"BadAggregateInvalidInputs",
"The aggregate value could not be derived due to invalid data inputs."
],
"2161573888": [
"BadBoundNotFound",
"No data found to provide upper or lower bound value."
],
"2161639424": [
"BadBoundNotSupported",
"The server cannot retrieve a bound for the variable."
],
"2161770496": [
"BadAggregateConfigurationRejected",
"The aggregate configuration is not valid for specified node."
],
"2161836032": [
"BadTooManyMonitoredItems",
"The request could not be processed because there are too many monitored items in the subscription."
],
"2162229248": [
"BadDominantValueChanged",
"The related EngineeringUnit has been changed but this change has not been applied to the device. The Variable Value is still dependent on the previous unit but its status is currently Bad."
],
"2162360320": [
"BadDependentValueChanged",
"A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is Bad."
],
"2162425856": [
"BadRequestNotAllowed",
"The request was rejected by the server because it did not meet the criteria set by the server."
],
"2162491392": [
"BadTooManyArguments",
"Too many arguments were provided."
],
"2162556928": [
"BadSecurityModeInsufficient",
"The operation is not permitted over the current secure channel."
],
"2162622464": [
"BadDataSetIdInvalid",
"The DataSet specified for the DataSetWriter creation is invalid."
],
"2162688000": [
"BadTransactionPending",
"The operation is not allowed because a transaction is in progress."
],
"2162753536": [
"BadLocked",
"The requested operation is not allowed, because the Node is locked by a different application."
],
"2162819072": [
"BadIndexRangeDataMismatch",
"The written data does not match the IndexRange specified."
],
"2162950144": [
"BadRequiresLock",
"The requested operation is not allowed, because the Node is not locked by the application."
],
"2163015680": [
"BadLocaleNotSupported",
"The locale in the requested write operation is not supported."
],
"2163081216": [
"BadServerTooBusy",
"The Server does not have the resources to process the request at this time."
],
"2163212288": [
"BadNoValue",
"The variable has no default value and no initial value."
],
"2163277824": [
"BadTransactionFailed",
"The operation failed and all changes which were part of the transaction are rolled back."
],
"2165112832": [
"BadCertificateChainIncomplete",
"The certificate chain is incomplete."
],
"2165178368": [
"BadLicenseExpired",
"The server requires a license to operate in general or to perform a service or operation, but existing license is expired."
],
"2165243904": [
"BadLicenseLimitsExceeded",
"The server has limits on number of allowed operations / objects, based on installed licenses, and these limits where exceeded."
],
"2165309440": [
"BadLicenseNotAvailable",
"The server does not have a license which is required to operate in general or to perform a service or operation."
],
"2165374976": [
"BadNotExecutable",
"The executable attribute does not allow the execution of the method."
],
"2165440512": [
"BadNumericOverflow",
"The number was not accepted because of a numeric overflow."
],
"2165506048": [
"BadRequestNotComplete",
"The request has not been processed by the server yet."
],
"2165571584": [
"BadCertificatePolicyCheckFailed",
"The certificate does not meet the requirements of the security policy."
],
"2165637120": [
"BadAlreadyExists",
"An equivalent rule already exists."
],
"2165899264": [
"BadEdited_OutOfRange",
"It is delivered with a Variable value when Variable has changed but the value is not legal."
],
"2165964800": [
"BadInitialValue_OutOfRange",
"It is delivered with a Variable value when a source Variable has changed but the value is not legal."
],
"2166030336": [
"BadOutOfRange_DominantValueChanged",
"It is delivered with a dependent Variable value when a dominant Variable has changed and the value is not legal."
],
"2166095872": [
"BadEdited_OutOfRange_DominantValueChanged",
"It is delivered with a dependent Variable value when a dominant Variable has changed, the value is not legal and the change has not been applied."
],
"2166161408": [
"BadOutOfRange_DominantValueChanged_DependentValueChanged",
"It is delivered with a dependent Variable value when a dominant or dependent Variable has changed and the value is not legal."
],
"2166226944": [
"BadEdited_OutOfRange_DominantValueChanged_DependentValueChanged",
"It is delivered with a dependent Variable value when a dominant or dependent Variable has changed, the value is not legal and the change has not been applied."
],
"2166292480": [
"BadTicketRequired",
"The device identity needs a ticket before it can be accepted."
],
"2166358016": [
"BadTicketInvalid",
"The device identity needs a ticket before it can be accepted."
]
}
